"""add_long_video_fields

Revision ID: 8a44f5374053
Revises: 
Create Date: 2026-02-17 22:46:40.144022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a44f5374053'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('detailed_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('video', sa.Column('key_points_with_timestamps_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('video', sa.Column('recommendations_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('video', sa.Column('section_summaries_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('video', sa.Column('chunk_summaries_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('video', sa.Column('processing_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('video', sa.Column('chunks_processed', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('total_word_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_video_url'), 'video', ['url'], unique=False)
    op.create_index(op.f('ix_video_video_id'), 'video', ['video_id'], unique=False)
    op.drop_column('video', 'summary_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('summary_text', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_video_video_id'), table_name='video')
    op.drop_index(op.f('ix_video_url'), table_name='video')
    op.drop_column('video', 'total_word_count')
    op.drop_column('video', 'chunks_processed')
    op.drop_column('video', 'processing_method')
    op.drop_column('video', 'chunk_summaries_json')
    op.drop_column('video', 'section_summaries_json')
    op.drop_column('video', 'recommendations_json')
    op.drop_column('video', 'key_points_with_timestamps_json')
    op.drop_column('video', 'detailed_summary')
    # ### end Alembic commands ###
